---
format: 
  revealjs:
    title: "Principles of Microeconomics"
    author: Martin Andersen
    date: "Week 1"
    # incremental: true
    slide-number: true
    multiplex: true
    toc: true
    toc-depth: 1
    smaller: true
---
      


# About us



## About Me  
- Email: msander4@uncg.edu  
  - I will try to write back within 24-48 hours  
- Office hours (Bryan 456): Fridays from 10:30 AM - 12:30 PM   
  - By appointment (Bryan 448)  
- What do you want to know about me? (within reason)  

## testing a form
```{=html}
<iframe width="640px" height="480px" 
src="https://forms.microsoft.com/Pages/DesignPageV2.aspx?origin=NeoPortalPage&subpage=design&id=9Vzhc7tdr0aoYnU5Fiadc5-qiUetSxdIr7xcbHDc42BUNEQ0SEFEUUdNQjJVNFMzQUYzRjFBNkRIMy4u&topview=Presentation&embed=true"
frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>
```

<iframe width="640px" height="480px" src="https://forms.microsoft.com/Pages/ResponsePage.aspx?id=9Vzhc7tdr0aoYnU5Fiadc5-qiUetSxdIr7xcbHDc42BURE5YQzM5SksxR1JVMEQ0TTE5RFI5NFpITC4u&embed=true&topview=Presentation" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

## Getting to Know You (and Each Other)  
- Talk to each other  
  - Who is sitting near you?  
  - What major(s)?  
  - Do they live on campus?  
  - How can you reach them for help with the class?  
- Take five minutes to do this  



# About the class


## Classroom Rules and Expectations  
- No talking, eating, cheating, disrespecting, or sleeping  
- No texting, emailing, chatting, or other non-class-related phone use  
- Questions are welcome, but please don’t dominate the class  
- Show up to EVERY class  
- Take notes  
  - Write down things that seem important to you, questions you have, etc.  
- Read your notes, especially before exams!  



## Goals for Today’s Class  
1. Learning objectives
2. Course set up  
3. Value of economics  
4. What do UNCG economists do?  



## Learning objectives
- MAC - Critical Thinking and Inquiry in the Social and Behavioral Sciences:
  - Critically analyze claims, arguments, artifacts or information.
  -	Construct coherent, evidence-based arguments.

- Course Learning Objectives
  1.	Demonstrate how scarcity forces trade-offs, how every choice has an opportunity cost, and how different opportunity costs give rise to comparative advantages.
  2.	Apply knowledge of supply and demand, market equilibrium and elasticity to demonstrate how price allocates scarce resources.
  3.	Explain how markets reach efficient outcomes, why markets sometimes fail, and how government intervention can impact markets.
  4.	Describe a firm’s production process and resulting cost structure and show how output decisions are made.
  5.	Distinguish between perfectly competitive and monopolistic markets and understand the implications of each on market efficiency.




# Course set up (a typical week)
## Course Set-Up  
- Most weeks we will cover one content Module  
- There are eleven content Units and three exams  
  - See course home page for a detailed list of modules  



## The Typical Cycle of the Course  
1. **Packback Discussions**  
   - Intended to show how to apply economics outside of the classroom  
   - Each assignment requires:  
     - One question, due Tuesday night  
     - Two responses, due Friday night  


# Grading and assessment
## Grading  
- **Exams**: 50%  
  - Each exam counts for 15% of your total grade  
  - 5% bonus weight on your BEST exam  
- **Module textbook homework**: 40%  
- **Packback**: 10%  



## Final Grades  
- Final numeric grade is converted to a letter grade  
- I do NOT round up  
- Typically, I DO NOT provide extra credit opportunities  

# Materials

## The Textbook  
- The textbook is fully digital and interactive  
- Access via "Course Materials" in Canvas or at the UNCG bookstore  
- Earn points for reading and answering questions  


# Why economics?
## Economics in daily life

## Economics and careeers

# How to succeed in ECO 201
## Tips for success
## Resources available to you






## What Do Economists Actually Do?  
- Use theoretical and empirical models to:  
  1. Evaluate programs  
  2. Study human behavior  
  3. Explain social phenomena  



## Why Study (Micro) Economics?  
- Provides a theoretical model of how the world “works”  
- Develops analytical thinking and critical problem-solving skills  
- Supports acquiring quantitative, statistical, data, and computer skills  
- Helps formulate and analyze business strategies and public policies  



## Economists at UNCG Study  
- Labor markets  
- Innovation  
- Health and health insurance  
- Environmental policy  
- Education  
- Credit and lending markets  
- Interest rates  
- … and lots more things  



## Thinking Like an Economist – How Much Should You Study?  
- **Studying**  
  - Creates marginal benefits (benefit of each additional minute spent studying)  
- **Partying**  
  - Creates marginal costs of studying (value of each additional minute spent partying)  
- Find the "Goldilocks point" where marginal benefit equals marginal cost  
